Repository flamencist/ldap4net, pull requests merged in 2020-05, with the labels that each got.

#28 Fixed access modifiers in DirectoryAttribute
  LdapForNet/LdapEntry.cs
Labels: 2.4, bug

#37 add GetLdapOption method
  LdapForNet.Tests/LdapConnectionTests.cs
  LdapForNet/ILdapConnection.cs
  LdapForNet/LdapConnection.cs
  LdapForNet/Native/LdapNativeWindows.cs
  LdapForNet/Native/NativeMethodsWindows.cs
Labels: 2.5

#38 support ldap v3 search controls
  .test_config/apparmor.sh
  .test_config/slapd.linux.conf
  .travis.yml
  .vscode/launch.json
  .vscode/settings.json
  .vscode/tasks.json
  Examples/C#/LdapExample.Net/LdapExample.Net.csproj
  Examples/C#/LdapExample.Net/packages.config
  Examples/C#/LdapExample.csproj
  Examples/C#/Program.cs
  Examples/C/Makefile
  Examples/C/lber_example.c
  Examples/JS/pagesearch.js
  LdapForNet.Tests/BerConverterTests.cs
  LdapForNet.Tests/LdapConnectionTests.cs
  LdapForNet/BerConverter.cs
  LdapForNet/DirectoryControl.cs
  LdapForNet/DirectoryRequest.cs
  LdapForNet/DirectoryResponse.cs
  LdapForNet/ILdapConnection.cs
  LdapForNet/LdapConnection.cs
  LdapForNet/LdapHandle.cs
  LdapForNet/LdapOperation.cs
  LdapForNet/Native/LdapNative.cs
  LdapForNet/Native/LdapNativeLinux.cs
  LdapForNet/Native/LdapNativeOsx.cs
  LdapForNet/Native/LdapNativeWindows.cs
  LdapForNet/Native/Native.LDAPMod.cs
  LdapForNet/Native/NativeMethodsLinux.cs
  LdapForNet/Native/NativeMethodsOsx.cs
  LdapForNet/Native/NativeMethodsWindows.cs
  LdapForNet/RequestHandlers/AbandonRequestHandler.cs
  LdapForNet/RequestHandlers/AddRequestHandler.cs
  LdapForNet/RequestHandlers/CompareRequestHandler.cs
  LdapForNet/RequestHandlers/DeleteRequestHandler.cs
  LdapForNet/RequestHandlers/ExtendedRequestHandler.cs
  LdapForNet/RequestHandlers/LdapSearchResultReference.cs
  LdapForNet/RequestHandlers/ModifyDnRequestHandler.cs
  LdapForNet/RequestHandlers/ModifyRequestHandler.cs
  LdapForNet/RequestHandlers/RequestHandler.cs
  LdapForNet/RequestHandlers/SearchRequestHandler.cs
  LdapForNet/RequestHandlers/TransportLayerSecurityRequestHandler.cs
  LdapForNet/Utils/MarshalUtils.cs
  README.md
Labels: 2.5

#39 add response to exception
  LdapForNet/LdapConnection.cs
  LdapForNet/LdapException.cs
Labels: 2.5

#41 add connection timeout
  LdapForNet.sln.DotSettings
  LdapForNet/ILdapConnection.cs
  LdapForNet/LdapConnection.cs
  LdapForNet/Native/LdapNative.cs
  LdapForNet/Native/LdapNativeLinux.cs
  LdapForNet/Native/LdapNativeOsx.cs
  LdapForNet/Native/LdapNativeWindows.cs
  LdapForNet/Native/NativeMethodsLinux.cs
  LdapForNet/Native/NativeMethodsOsx.cs
  LdapForNet/Native/NativeMethodsWindows.cs
  README.md
Labels: 2.5

#42 Version 2.5
  LdapForNet/LdapForNet.csproj
  README.md
Labels: 2.5

#45 Added parsing attributes for DirectoryEntry
  LdapForNet.Tests/LdapConnectionTests.cs
  LdapForNet/LdapAttributes.cs
  LdapForNet/LdapEntry.cs
  LdapForNet/UserAccountControl.cs
Labels: 2.6
